meta:
  id: "squad_recon_elimination"
  name: "Squad Reconnaissance and Elimination"
  description: "Tactical military scenario where squads must locate and eliminate hidden enemy camps"

state_template:
  globals:
    max_steps: 40
    grid_size: [15, 15]
    total_enemy_camps: 2
    eliminated_camps: 0
  squads:
    - id: 0
      pos: [1, 1]
      strength: 3
      active: true
    - id: 1
      pos: [2, 1] 
      strength: 3
      active: true
    - id: 2
      pos: [1, 2]
      strength: 3
      active: true
  enemy_camps:
    - id: 0
      pos: [10, 10]
      strength: 4
      discovered: false
    - id: 1
      pos: [12, 8]
      strength: 3
      discovered: false
  terrain:
    size: [15, 15]
    default_type: "open"
    walls: []
    forests: []
  visibility_map:
    explored: []

observation:
  policy: "fog_of_war_tactical"
  params:
    sensor_radius: 3
  expose:
    - squads
    - discovered_enemy_camps
    - tactical_map
    - globals.eliminated_camps
    - globals.total_enemy_camps
    - globals.max_steps
    - total_friendly_strength
    - t

reward:
  events:
    - trigger: "enemy_camp_eliminated" 
      value_key: "camp_rewards"
  camp_rewards:
    first_camp: 0.5
    second_camp: 0.5

transition:
  actions:
    - name: "HOLD_POSITION"
      params: [squad_id]
    - name: "MOVE_NORTH"
      params: [squad_id]
    - name: "MOVE_SOUTH" 
      params: [squad_id]
    - name: "MOVE_EAST"
      params: [squad_id]
    - name: "MOVE_WEST"
      params: [squad_id]
    - name: "ATTACK_ENEMY_CAMP"
      params: [squad_id, camp_id]

skin:
  type: "text"
  template: |
    === TACTICAL SITUATION REPORT ===
    Step: {t}/{max_steps}
    Mission Progress: {eliminated_camps}/{total_enemy_camps} enemy camps eliminated
    
    SQUAD STATUS:
    {squad_status}
    
    TACTICAL MAP (15x15):
    {tactical_map_ascii}
    
    LEGEND: S=Squad, E=Enemy Camp, #=Wall, T=Forest, .=Open, ?=Unexplored
    
    Total Friendly Strength: {total_friendly_strength}
    
    Available Actions: HOLD_POSITION(squad_id), MOVE_NORTH/SOUTH/EAST/WEST(squad_id), ATTACK_ENEMY_CAMP(squad_id, camp_id)

termination:
  max_steps: 40
  conditions:
    - "globals.eliminated_camps >= globals.total_enemy_camps"
    - "all squads destroyed"

generator:
  mode: "procedural"
  output_format: "yaml"
  pipeline:
    - name: "init_from_template"
      desc: "Initialize world with state_template as base"
      args: {}
    - name: "randomize_squad_strength"
      desc: "Assign random strength 1-4 to each squad"
      args:
        min_strength: 1
        max_strength: 4
    - name: "generate_terrain"
      desc: "Place walls and forest patches strategically across 15x15 grid"
      args:
        wall_density: 0.15
        forest_density: 0.1
    - name: "place_enemy_camps"
      desc: "Randomly place 2 enemy camps avoiding walls/forests/spawn area"
      args:
        num_camps: 2
        min_strength: 2
        max_strength: 6
        min_distance_from_spawn: 5
    - name: "initialize_fog_of_war"
      desc: "Set all positions as unexplored except initial squad sensor ranges"
      args:
        sensor_radius: 3

  randomization:
    seed_based: true
    parameters:
      squad_strength_range: [1, 4]
      enemy_strength_range: [2, 6]
      terrain_density: [0.1, 0.3]

world_loading:
  directory: "worlds/{env_id}/"
  format: "yaml"
  validation_schema: "state_template"
  naming_convention: "{world_id}.yaml"

misc:
  logging: true
  store_rollouts: true
  debug_mode: false